version: '3.8'

# Alternative Docker Compose configuration for host network
# Note: With WebRTC, this is no longer needed but kept for compatibility

services:
  attendance-app:
    build: .
    container_name: attendance-recognition-webrtc-host
    network_mode: host
    volumes:
      - ./users:/app/users
      - ./attendance_collections:/app/attendance_collections
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PORT=8082
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"