version: '3.8'

services:
  attendance-app:
    build: .
    container_name: attendance-recognition-system
    ports:
      - "8082:5000"
    volumes:
      - ./users:/app/users
      - ./attendance_collections:/app/attendance_collections
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # NETWORK CAMERA EXAMPLES:
      # For RTSP cameras:
      # - CAMERA_SOURCE=rtsp://user:password@192.168.1.100:554/stream1
      # For IP Webcam (Android app):
      # - CAMERA_SOURCE=http://192.168.1.101:8080/video
      # For MJPEG HTTP streams:
      # - CAMERA_SOURCE=http://192.168.1.102:8081/mjpg/video.mjpg
      # For local camera device (fallback):
      # - CAMERA_SOURCE=0
      - CAMERA_SOURCE=${CAMERA_SOURCE:-0}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: attendance-network
